name: Maintain Contribution Streak

on:
  push:
    branches:
      - main  # change to 'master' if needed
  schedule:
    - cron: "0 23 * * *"  # every day at 23:00 UTC
  workflow_dispatch:

jobs:
  touch-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Detect today's commit activity
        id: activity_check
        run: |
          LAST_COMMIT_DATE=$(git log -1 --format=%cd --date=short)
          TODAY=$(date -u +'%Y-%m-%d')

          echo "Last commit date: $LAST_COMMIT_DATE"
          echo "Today: $TODAY"

          if [ "$LAST_COMMIT_DATE" = "$TODAY" ]; then
            echo "activity=true" >> $GITHUB_ENV
          else
            echo "activity=false" >> $GITHUB_ENV
          fi

      - name: Rewrite readme.md (no real change)
        run: |
          cp readme.md readme.tmp && mv readme.tmp readme.md

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ "$activity" = "true" ]; then
            COMMIT_MESSAGE="ci: auto-updated readme.md after push activity"
          else
            COMMIT_MESSAGE="ci: auto-updated readme.md (no activity detected)"
          fi

          git add readme.md
          git commit -m "$COMMIT_MESSAGE" || echo "No changes to commit"

          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
