name: Update README with Repo List

on:
  push:
    branches:
      - main
      - master
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update README with Repo List
        uses: varunsridharan/action-repository-list@main
        with:
          # Your GitHub username
          username: 'abdulrehmangulfaraz'
          
          # The header for the list
          header: '### 📚 My Other Projects'
          
          # How to format each repository in the list
          # Available variables: %name%, %url%, %description%, %language%, %stars%, %forks%
          item-style: '- [%name%](%url%)'

          # Maximum number of repositories to list
          max: 12

          # How to sort the repositories
          sort_by: 'pushed'
          sort_order: 'desc'
          
          # The comments in your README to place the list between
          start: ''
          end: ''
          
          # A comma-separated list of repos to exclude (your featured ones)
          exclude: 'CodeDawn,Aqshmar,Chess-Game-MASM32'