name: Update README with Repo List

on:
  push:
    branches:
      - main
      - master
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README
        uses: athul/guzaarish@v1
        with:
          # Your GitHub token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Repositories to exclude (your featured ones)
          EXCLUDE: "CodeDawn,Aqshmar,Chess-Game-MASM32"